### ISSUE TITLE
Picks up vuex 'mapGetters' functions

### ISSUE THREAD

**Issue by dsl101** [Polarisation/vue-computed-promise#2]
`vue-computed-promise` has solved one of my problems (needing a computed prop which depends on a firebase promise resolving), but it has broken something in the process. This code used to work:

    computed: {
      pageName () {
        return this.loading ? null : this.__page(this.$route.params.page).name
      }
      ...mapGetters({
        loading: 'loading',
        __page: 'page'
      })
    }

but now throws an error:

    Error in render function: "Error: VueComputedPromise: __page function returned must return a Promise"

`loading` and `__page` are both synchronous getters defined in my Vuex store, but it looks like something about them is fooling `vue-computed-promise` to convert them to async?

**Comment by Polarisation** [comment]
Does `__page` return a function rather than a value? That's appears to be what is triggering the error...(https://github.com/Polarisation/vue-computed-promise/blob/90a99610d32bf6239f6d5a0a51c12d6bd0278b21/vue-computed-promise.js#L53)

It might be possible to fix this by simply changing that line to: `return result;`. You could try that to see if it helps.

But I don't understand why __page would return a function and what that would be expected to do. I don't see anything in the Vue.js documentation about handling a function returned from a computed getter method... perhaps you can explain.

**Comment by dsl101** [comment]
Yes, `page` does return a function, as it's a getter which requires a parameter, and that seemed to be the recommended approach - however I can't remember now where I got it from, and I'll take your word it wasn't from the Vue docs :). Perhaps it's out of spec and just happens to work.

This is the current definition of the getter `page`:

    export const page = state => pageID => state.event && state.event.pages && state.event.pages[pageID]

I should probably move `pageID` into the store, but that seems a bit strange, since the _only_ place it is needed is by that getter. Maybe there is a better way to define the getter which wouldn't trigger your module into picking it up? Or a way of defining VueComputedPromise which doesn't care if a function actually returns a promise or a value? But that might be lots of extra checks which hit performance...

I also looked at `vue-async-computed` - I preferred your model of keeping everything in `computed:`, but I guess this is the challenge of checking for whether the function actually needs wrapping. Using that other module I just move the definition of my _actual_ async props into `asyncComputed:`, and my regular computed props, including function-returning getters work ok, so perhaps in my specific case it's better to use that module...

**Comment by dsl101** [comment]
Also, in this specific case, I could use `vuex-router-sync`, as the `pageID` _is_ in the route. But that only solves this specific problem. There could be other function-returning getters that aren't based on the route, so a more general solution would be preferable. I found a few bits of advice from vue core team members saying function getters are OK - see [here](https://github.com/vuejs/vuex/issues/145#issuecomment-294963904) for example.

**Comment by Polarisation** [comment]
I see, the [Vuex getters documentation](https://vuex.vuejs.org/en/getters.html) does mention this. I've just been use plain Vue.js withut Vuex so had not come across this case, and I can't say I fully understand the use case but I clearly there is one. So I have added a check to ignore a function with parameters, I think fixes the issue. I've published this as 1.0.3

**Comment by dsl101** [comment]
Yup - all working perfectly now :). Many thanks for the quick update.
